//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarhatnieBrovki.DatabaseField
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.ClientServices = new HashSet<ClientServices>();
            this.ServicePhotoes = new HashSet<ServicePhotoes>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal cost;

        public decimal Cost
        {
            get
            {               
                return cost;
            }

            set
            {
                cost = value;
            }
        }

        [NotMapped]
        public decimal CostSet
        {
            get
            {
                if (Discount == null || Discount == 0) //если нет скидки
                    return cost;

                else
                {
                    return cost - (cost * ((decimal)Discount / 100));
                }
            }

            set
            {
                cost = value;
            }
        }


        [NotMapped]
        public decimal CostWithoutDiscount        
        { 
            get 
            {
                return cost; 
            } 
        }

        public int durationInSeconds;
        public int DurationInSeconds 
        {
            get
            {
                return durationInSeconds / 60;
            }

            set
            {
                durationInSeconds = value; 
            }
        }
        public string Description { get; set; }

        public Nullable<double> discount;
        public Nullable<double> Discount
        {
            get
            {
                return discount * 100;
            }

            set
            {
               discount = value;
            }
        }

      



        public string mainImagePath;
        public string MainImagePath
        {
            get
            {
                return  mainImagePath;
            }
            set
            {
               mainImagePath = value;
            }
        }

        [NotMapped]
        public string MainImagePathSet
        {
            get
            {
                return "pack://siteoforigin:,,,/" + mainImagePath;
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServices> ClientServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhotoes> ServicePhotoes { get; set; }
    }
}
